-- =========================================================================
-- enums.sql
-- Tipos enumerados (domínios fechados).
-- Estado ATUAL do banco para esta entidade.
-- =========================================================================
