-- =========================================================================
-- extensions.sql
-- Extensões do PostgreSQL (ex.: pgcrypto).
-- Estado ATUAL do banco para esta entidade.
-- =========================================================================
