-- =========================================================================
-- grants.sql
-- Grants por role (anon, authenticated, service_role) — menor privilégio.
-- Estado ATUAL do banco para esta entidade.
-- =========================================================================
