-- =========================================================================
-- storage.sql
-- Buckets e policies de storage.
-- Estado ATUAL do banco para esta entidade.
-- =========================================================================
